### ISSUE TITLE
[bug] LogCabin server can not restart

### ISSUE THREAD

**Issue by jujing** [logcabin/logcabin#191] opened 2015-09-07 11:57 UTC
Start a LogCabin server and kill it soon. Then restart it. Cannot start up with the following error message: 
2015-09-07 02:37:39.719750 Storage/SegmentedLog.cc:999 in loadOpenSegment() ERROR[1:evloop]: Segment version read from open-19 was 0, but this code can only read version 1 Exiting...

It is because in SegmentedLog::prepareNewSegment LogCabin want to allocate a 8M file for log entries, and has not set the first byte of file to 1 yet. Then we kill it. 
So in SegmentedLog::loadOpenSegment, LogCabin verify the version and found error. 
But I think it is better just WARNING here, and if it is All Zero, the following handling could remove this file. 
Otherwise, this LogCabin server can not start up, and user do not know how to do.

**Comment by ongardie** [comment] 2015-09-10 18:51
Good find. I think you're right: the server should treat a segment with a version of 0 and all zeros following as a non-issue. I don't think even a WARNING is necessary.

**Comment by ongardie** [comment] 2016-02-11 01:29
@jujing, do you have a patch for this one that you can contribute?

**Comment by ramanala** [comment] 2016-08-25 16:08
Here is much detailed explanation of the same bug (copied from #221):

I have three-node LogCabin cluster. If a power failure occurs at a certain point in time, the cluster becomes unavailable for future operations.

The workload I am running is very simple: Just inserting a new key and it corresponding value.

When LogCabin creates a new open segment file, it first creates the file, truncates it and then writes some metadata header to the starting of the file. The system call sequence looks like this;

1 creat("Segmented-Binary/open-4")
2 trunc("Segmented-Binary/open-4", initial_size=0, final_size=10240)
3 write("Segmented-Binary/open-4", count=10240, offset=0) 
4 write("Segmented-Binary/open-4", count=1, offset=0)

Now, if a crash happens just after operation 3 but before operation 4, then this node would not start with this following error in its log:

016-04-16 21:59:54.779695 Server/Main.cc:305 in main() NOTICE[32712:evloop]: Using config file /tmp/lc2.cfg
2016-04-16 21:59:54.780124 Server/Main.cc:345 in main() NOTICE[32712:evloop]: Config file settings:
begin config
listenAddresses = 127.0.0.2:5254
serverId = 1
storageOpenSegments = 0
storagePath = /my_raft_log
storageSegmentBytes = 10240
end config
2016-04-16 21:59:54.780431 Server/Globals.cc:172 in init() NOTICE[1:evloop]: Serving on 127.0.0.2:5254 (resolved to 127.0.0.2:5254)
2016-04-16 21:59:54.780452 Server/RaftConsensus.cc:1041 in init() NOTICE[1:evloop]: My server ID is 1
2016-04-16 21:59:54.780553 Server/RaftConsensus.cc:1053 in init() NOTICE[1:evloop]: Reading the log
2016-04-16 21:59:54.780804 Storage/SegmentedLog.cc:898 in readMetadata() NOTICE[1:evloop]: Read metadata version 9 from metadata1
2016-04-16 21:59:54.780851 Storage/SegmentedLog.cc:898 in readMetadata() NOTICE[1:evloop]: Read metadata version 10 from metadata2
2016-04-16 21:59:54.780872 Storage/SegmentedLog.cc:778 in updateMetadata() NOTICE[1:evloop]: Writing new storage metadata (version 11) to metadata1
2016-04-16 21:59:54.780921 Storage/SegmentedLog.cc:778 in updateMetadata() NOTICE[1:evloop]: Writing new storage metadata (version 12) to metadata2
2016-04-16 21:59:54.781299 Storage/SegmentedLog.cc:998 in loadOpenSegment() ERROR[1:evloop]: Segment version read from open-4 was 0, but this code can only read version 1 Exiting...

The above sequence of operations happen on all three nodes. Now if two nodes crash exactly at this same point, the entire cluster becomes unusable as as majority of servers have gone down. It is even possible for all three nodes to crash at this exact point in time. A power failure at the same time across multiple nodes may be possible in single data center or single rack deployment scenarios.

**Comment by nhardt** [comment] 2016-08-25 16:11
This is on my radar as something to fix. The fix I had in mind in the case the segment loads as version 0 is to scan it to see if it is all 0s. If so, delete it and move on. Do we need anything more involved than that?

**Comment by ongardie** [comment] 2016-08-25 16:15
I think that's it, @nhardt, and there's already a function to test a byte range for zeros somewhere in there. A unit test showing the fix would be good too (artificially write out a file with a bunch of zeros on disk, then create the store and make sure it doesn't panic).

@jujing or @ramanala, did you have a fix for this already that you could contribute?

**Comment by ramanala** [comment] 2016-08-25 16:25
@ongardie @nhardt 

I believe the problem is bit more subtle here if we need to get a correct fix for this. If you see the sequence of operations, LogCabin truncates the segment file after creation. If the truncation always ends up in populating the data blocks with zeros, then the prescribed fix would work. But on few file systems (such as ext3 or ext4 in writeback mode), it may be possible for a crash during the truncate to leave the file with garbage. I agree that it is very rare but can certainly happen on few file systems. In case we do not want to fix that scenario, then probably, it would be a good idea to document it somewhere mentioning that problems may surface if you run LogCabin on such file system configurations. 

On the fix part, I don't have a fix right now but can work on it a little later.

**Comment by ongardie** [comment] 2016-08-25 17:26
> But on few file systems (such as ext3 or ext4 in writeback mode), it may be possible for a crash during the truncate to leave the file with garbage. I agree that it is very rare but can certainly happen on few file systems.

Eww. Is writeback mode a common configuration, or should these people know when they enable it that they're asking for trouble?

**Comment by ramanala** [comment] 2016-08-25 17:57
I don't think writeback is a commonly-used configuration. But these subtle properties are not generally well known (Please refer to https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-pillai.pdf ). When the study was performed, only the writeback mode seemed to exhibit this subtle behavior (i.e., truncates can end up in garbage). In the future, we are not sure if this behavior can be encountered in most commonly-used modes such as the ordered mode (in ext3 and ext4). I am saying this because, these behaviors are subtle and can change accidentally when FS developers "fix" some performance issues.

Since subtle troubles in modes such as writeback are not well documented, people expect them to work correctly. So, if we want a perfect fix for this issue, we may have to take care of garbage, not just zeros. Otherwise, we can fix the case for zeros and explicitly document that users may see unexpected problems when their file system can leave files with garbage on a truncate operation.

**Comment by nhardt** [comment] 2016-08-25 19:40
From a disaster recovery standpoint, I think I would be against automatically deleting and ignoring what looks to be a log full of garbage. Zeros I'm fine with automatically deleting, but I think I want LogCabin to stop what it is doing if it encounters log corruption. That might require human intervention to save data. It might also highlight that someone's file system is not behaving in line with the guarantees LogCabin is built on, for example that disk writes really go do disk when you ask them to. So, I've made a patch for the commonly seen all 0s situation but have not attempted to address corrupted log segments.

**Comment by ongardie** [comment] 2016-08-25 21:47
Yeah, I agree with @nhardt. In the odd case that a filesystem leaves garbage in a segment, LogCabin is probably doing the right thing by panicking and crying out for help.

**Comment by ongardie** [comment] 2016-08-25 21:48
If that was truly expected behavior, we'd have to redesign to make that detectable in a reliable way. But I don't think that's worth it for a broken fs/config.

**Comment by ramanala** [comment] 2016-08-25 22:50
I agree since truncates can leave the file with garbage only in rare mount options.  
Thanks @ongardie  and @nhardt for the discussion. 
@nhardt -- thanks for fixing the bug!

**Comment by ongardie** [comment] 2016-08-25 23:05
Alright, merged #222, so I'll close this issue. Thanks @jujing @ramanala and @nhardt.

**Closed** 2016-08-25 23:05 UTC
Labels: bug
