### ISSUE TITLE
LogCabin cluster can become unavailable due to power failures

### ISSUE THREAD

**Issue by ramanala** [logcabin/logcabin#221] opened 2016-08-25 14:34 UTC
I have three-node LogCabin cluster. If a power failure occurs at a certain point in time, the cluster becomes unavailable for future operations. 

The workload I am running is very simple: Just inserting a new node and it corresponding value. 

When LogCabin creates a new open segment file, it first creates the file, truncates it and then writes some metadata header to the starting of the file. The system call sequence looks like this;

**1** creat("Segmented-Binary/open-4")
**2** trunc("Segmented-Binary/open-4", initial_size=0,  final_size=10240)
**3** write("Segmented-Binary/open-4", count=10240, offset=0) 
**4** write("Segmented-Binary/open-4", count=1, offset=0)

Now, if a crash happens just after operation 3 but before operation 4, then this node would not start with this following error in its log:

016-04-16 21:59:54.779695 Server/Main.cc:305 in main() NOTICE[32712:evloop]: Using config file /tmp/lc2.cfg
2016-04-16 21:59:54.780124 Server/Main.cc:345 in main() NOTICE[32712:evloop]: Config file settings:
begin config
listenAddresses = 127.0.0.2:5254
serverId = 1
storageOpenSegments = 0
storagePath = /my_raft_log
storageSegmentBytes = 10240
end config
2016-04-16 21:59:54.780431 Server/Globals.cc:172 in init() NOTICE[1:evloop]: Serving on 127.0.0.2:5254 (resolved to 127.0.0.2:5254)
2016-04-16 21:59:54.780452 Server/RaftConsensus.cc:1041 in init() NOTICE[1:evloop]: My server ID is 1
2016-04-16 21:59:54.780553 Server/RaftConsensus.cc:1053 in init() NOTICE[1:evloop]: Reading the log
2016-04-16 21:59:54.780804 Storage/SegmentedLog.cc:898 in readMetadata() NOTICE[1:evloop]: Read metadata version 9 from metadata1
2016-04-16 21:59:54.780851 Storage/SegmentedLog.cc:898 in readMetadata() NOTICE[1:evloop]: Read metadata version 10 from metadata2
2016-04-16 21:59:54.780872 Storage/SegmentedLog.cc:778 in updateMetadata() NOTICE[1:evloop]: Writing new storage metadata (version 11) to metadata1
2016-04-16 21:59:54.780921 Storage/SegmentedLog.cc:778 in updateMetadata() NOTICE[1:evloop]: Writing new storage metadata (version 12) to metadata2
2016-04-16 21:59:54.781299 Storage/SegmentedLog.cc:998 in loadOpenSegment() ERROR[1:evloop]: Segment version read from open-4 was 0, but this code can only read version 1 Exiting...

The above sequence of operations happen on all three nodes. Now if two nodes crash exactly at this same point, the entire cluster becomes unusable as as majority of servers have gone down. It is even possible for all three nodes to crash at this exact point in time. A power failure at the same time across multiple nodes may be possible in single data center or single rack deployment scenarios.

**Comment by ongardie** [comment] 2016-08-25 15:51
Thanks @ramanala, that's an awesome description but I think the issue is a duplicate of #191 (which has, unfortunately, sat for too long). Can you add your description as a comment on #191 and close this one?

**Closed** 2016-08-25 16:08 UTC

**Comment by ramanala** [comment] 2016-08-25 16:13
This bug was discovered in our efforts to find correlated crash problems in distributed storage systems. It is possible for all or a majority of nodes to be at the exact point where operation 3 had completed but just before operation 4.  The underlying reason seems to be that the truncate of the segment and header write need to be atomically persisted -- i.e., the nodes can recover without any problems if they crashed    just after operation 4 was persisted. #191 also seems to have hit this same underlying issue just by crashing the LogCabin process.

**Comment by ongardie** [comment] 2016-08-25 16:18
It's not that (3) and (4) need to be atomic, and posix gives you no way of expressing that anyway. It's just that on startup after (3), the code shouldn't panic. There can't be anything on the segment before the header was written, so it's ok to delete and ignore it.

**Comment by ongardie** [comment] 2016-08-25 16:19
Oh I should say, thanks for running your tests! Please send a link to the blog post/paper on logcabin-dev once you have it :)

**Comment by ramanala** [comment] 2016-08-25 16:27
Yes, I agree that expressing such atomicity with Posix is not possible and that the recovery code should just expect the worst. Sure, I will share the paper soon.
